modoboa/core/urls.py
"""Core urls."""

from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns(
    '',

    url(r'^$', views.RootDispatchView.as_view(), name="root"),
    url(r'^dashboard/$', views.DashboardView.as_view(), name="dashboard"),

    url(r'^accounts/login/$', 'modoboa.core.views.auth.dologin',
        name="login"),
    url(r'^accounts/logout/$', 'modoboa.core.views.auth.dologout',
        name="logout"),

    url(r'^core/$', 'modoboa.core.views.admin.viewsettings',
        name="index"),
    url(r'^core/parameters/$', 'modoboa.core.views.admin.viewparameters',
        name="parameter_listl"),
    url(r'^core/parameters/save/$', 'modoboa.core.views.admin.saveparameters',
        name="parameter_save"),
    url(r'^core/info/$', 'modoboa.core.views.admin.information',
        name="information"),
    url(r'^core/logs/$', 'modoboa.core.views.admin.logs', name="log_list"),
    url(r'^core/logs/page/$', 'modoboa.core.views.admin.logs_page',
        name="logs_page"),
    url(r'^core/top_notifications/check/$',
        'modoboa.core.views.admin.check_top_notifications',
        name='top_notifications_check'),

    url(r'^user/$', 'modoboa.core.views.user.index', name="user_index"),
    url(r'^user/preferences/$', 'modoboa.core.views.user.preferences',
        name="user_preferences"),
    url(r'^user/profile/$', 'modoboa.core.views.user.profile',
        name="user_profile"),
    url(r'^user/api/$', 'modoboa.core.views.user.api_access',
        name="user_api_access"),
)

modoboa/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

from modoboa.core.extensions import exts_pool
from modoboa.lib import events


urlpatterns = patterns(
    '',
    (r'^jsi18n/$', 'django.views.i18n.javascript_catalog',
     {'packages': ('modoboa', ), }),
    ('', include('modoboa.core.urls', namespace="core")),
    url('^user/forward/', 'modoboa.admin.views.user.forward',
        name='user_forward'),
    ('admin/', include('modoboa.admin.urls', namespace="admin")),
    ('relaydomains/',
     include('modoboa.relaydomains.urls', namespace="relaydomains")),
)

urlpatterns += patterns(
    '',
    *exts_pool.load_all()
)

urlpatterns += patterns(
    '',
    *events.raiseQueryEvent("ExtraUprefsRoutes")
)

# API urls
urlpatterns += patterns(
    "",
    ("^api/v1/", include("modoboa.urls_api", namespace="external_api")),
    url("^docs/api/", include('rest_framework_swagger.urls')),
)

if 'modoboa.demo' in settings.INSTALLED_APPS:
    urlpatterns += patterns(
        '',
        (r'^demo/', include('modoboa.demo.urls', namespace="demo"))
    )

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    from django.conf.urls.static import static
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

modoboa/templates/fluid.html
{% extends "nlayout.html" %}
{% block content %}
<div class="container-fluid">
  {% block container_content %}{% endblock %}
</div>
{% endblock %}

modoboa/templates/layout_simple.html
<!DOCTYPE html>
{% load static %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8" />
    <title>{% block pagetitle %}{% endblock %}</title>
    <link rel="icon" type="image/png" href="{% static 'css/logo-icon.png' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" />
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js' %}" type="text/javascript"></script>
    {% url "django.views.i18n.javascript_catalog" as catalog_url %}
    <script type="text/javascript" src="{{ catalog_url }}"></script>
    <style>
      body {
          padding-top: 60px;
      }
    </style>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row-fluid">
        {% block content %}{% endblock %}
      </div>
    </div>
  </body>
</html>

modoboa/templates/nlayout.html
<!DOCTYPE html>
{% load static %}
{% load i18n core_tags lib_tags %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>{% block pagetitle %}{% endblock %}</title>
    <link rel="icon" type="image/png" href="{% static 'css/logo-icon.png' %}" />
    <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css' %}" />
    <link rel="stylesheet" href="{% static 'bootstrap-select/dist/css/bootstrap-select.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}" />
    {% block extra_css %}{% endblock %}
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">

          <button class="navbar-toggle collapsed pull-right" data-target="#topmenu" data-toggle="collapse" type="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <button class="navbar-toggle collapsed pull-left" data-target="#leftcol" data-toggle="collapse" type="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>


        <div id="topmenu" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% if user.is_admin %}
              <li{% if selection == "dashboard" %} class="active"{% endif %}>
                <a name="dashboard" href="{% url 'core:dashboard' %}">
                  <span class="fa fa-home fa-lg"></span>
                </a>
              </li>
            {% endif %}
            {% if selection %}
              {% extensions_menu selection user %}{% core_menu selection user %}
            {% else %}
              {% extensions_menu "" user %}{% core_menu "" user %}
            {% endif %}
            {% load_optionalmenu user %}
            <li class="divider"></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if selection %}{% user_menu user selection %}{% else %}{% user_menu user "" %}{% endif %}
          </ul>
          {% include "common/top_notifications.html" %}
        </div>
      </div>
    </div>

    {% block content %}{% endblock %}

    <!-- Javascript -->
    <script src="{% static 'jquery/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}" type="text/javascript"></script>
    <script type="text/javascript" src="{% static 'moment/min/moment.min.js' %}"></script>
    <script src="{% static 'eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'bootstrap-select/dist/js/bootstrap-select.min.js' %}" type="text/javascript"></script>
    {% if LANGUAGE_CODE != "en" %}<script src="{{ STATIC_URL }}moment/locale/{{ LANGUAGE_CODE }}.js" type="text/javascript"></script>{% endif %}
    {% if TEMPLATE_DEBUG %}
      <script src="//maxcdn.bootstrapcdn.com/bootlint/0.4.0/bootlint.min.js"></script>
    {% endif %}
    <script src="{% static 'js/global.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/csrf.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/confirmation.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/notify.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/poller.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/top_notifications.js' %}" type="text/javascript"></script>
    {% url "django.views.i18n.javascript_catalog" as catalog_url %}
    <script type="text/javascript" src="{{ catalog_url }}"></script>
    <script type="text/javascript">
      var top_notifications;

      set_static_url("{{ STATIC_URL }}");
      $(document).ready(function() {
          top_notifications = new TopNotifications({
              url: "{% url 'core:top_notifications_check' %}",
              interval: {{ notifications_check_interval }}
          });
      });
    </script>
    {% extra_static_content "top" "js" user %}
    {% block extra_js %}{% endblock %}
  </body>
</html>

modoboa/templates/twocols.html
{% extends "fluid.html" %}

{% load core_tags %}

{% block container_content %}
<div id="leftcol" class="sidebar collapse navbar-collapse">
  {% block leftcol %}{% endblock %}
</div>
<div class="main">
  {% if messages %}{% display_messages messages %}{% endif %}
  {% block apparea %}{% endblock %}
</div>
{% endblock %}